import p1_img from "../Videos & Images/foundation 1.jpeg"
import p2_img from "../Videos & Images/foundation 2.jpeg"
import p3_img from "../Videos & Images/foundation 3.jpeg"
import p4_img from "../Videos & Images/foundation 4.jpeg"
import p5_img from "../Videos & Images/foundation 5.jpg"
import p6_img from "../Videos & Images/lipstick 1.jpeg"
import p7_img from "../Videos & Images/lipstick 2.png"
import p8_img from "../Videos & Images/lipstick3.jpg"
import p9_img from "../Videos & Images/lildstick4.jpeg"
import p10_img from "../Videos & Images/lipstick 5.jpeg"
import p11_img from "../Videos & Images/brush1.jpeg"
import p12_img from "../Videos & Images/brush2.jpg"
import p13_img from "../Videos & Images/brush3.jpg"
import p14_img from "../Videos & Images/brush4.jpeg"
import p15_img from "../Videos & Images/brush5.jpeg"
import p16_img from "../Videos & Images/eyelashes1.jpeg"
import p17_img from "../Videos & Images/eyelashes 2.jpeg"
import p18_img from "../Videos & Images/eyelashes 3.jpeg"
import p19_img from "../Videos & Images/eyelashes 4.jpeg"
import p20_img from "../Videos & Images/eyelashes 5.jpeg"
import p21_img from "../Videos & Images/eyepallet1.jpeg"
import p22_img from "../Videos & Images/eyepallet2.jpeg"
import p23_img from "../Videos & Images/eyepallet3.jpeg"
import p24_img from "../Videos & Images/makeup pallet 5.jpeg"
import p25_img from "../Videos & Images/eyepallet5.jpg"
import p26_img from "../Videos & Images/cleanser1.jpeg"
import p27_img from "../Videos & Images/cleanser 2.jpeg"
import p28_img from "../Videos & Images/cleanser 3.jpeg"
import p29_img from "../Videos & Images/cleanser 4.jpeg"
import p30_img from "../Videos & Images/cleanser5.jpeg"



const ProductData = [
  { id: 1, 
    name: "Black Up Pinceau Strobing",
    category: "Foundation",
    image: p1_img, 
    new_price: 35000,
    old_price: 40000.00,
  },
  { id: 2, 
    name: "UODO Liquid Foundation",
    category: "Foundation",
    image: p2_img,     
    new_price: 55000.00,
    old_price: 60000.00,
  },
  { id: 3, 
    name: "Dermacol Makeup Foundation ",
    category: "Foundation",
    image: p3_img, 
    new_price: 30000.00,
    old_price: 40000.00,
  },
  { id: 4, 
    name: "Waterproof Foundation",
    category: "Foundation",
    image: p4_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 5, 
    name: "Matte Foundation ",
    category: "Foundation",
    image: p5_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 6, 
    name: "O FACE Satin Lipstick",
    category: "Lipstick",
    image: p6_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 7, 
    name: "Caviar Hydra-Creme Lipstick",
    category: "Lipstick",
    image: p7_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 8, 
    name: "Bella Keen Liquid Lipstick",
    category: "Lipstick",
    image: p8_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 9, 
    name: "Matte Lipstick",
    category: "Lipstick",
    image: p9_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 10, 
    name: "Moisturizing Liquid Lipstick",
    category: "Lipstick",
    image: p10_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 11, 
    name: "Blossome Makeup Brush Set",
    category: "Brush",
    image: p11_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 12, 
    name: "GENUINE AVON Makeup Brush Set",
    category: "Brush",
    image: p12_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 13, 
    name: "MAGEFY Makeup Brush Set",
    category: "Brush",
    image: p13_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 14, 
    name: "Beautykink Classic Makeup Brush",
    category: "Brush",
    image: p14_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 15, 
    name: "BS-MALL Makeup Brush Set",
    category: "Brush",
    image: p15_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 16, 
    name: "Wispy Lashes",
    category: "Eyelashes",
    image: p16_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 17, 
    name: "Catchy Eyelash",
    category: "Eyelashes",
    image: p17_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 18, 
    name: "3D Silk Lashes",
    category: "Eyelashes",
    image: p18_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 19, 
    name: "3D Faux Mink Lashes",
    category: "Eyelashes",
    image: p19_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 20, 
    name: "Strip Lashes",
    category: "Eyelashes",
    image: p20_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 21, 
    name: "The Signature Eyeshadow",
    category: "Palette",
    image: p21_img, 
    new_price: 60000.00,
    old_price: 70000.00,
  },
  { id: 22, 
    name: "Classic Makeup Eyeshadow",
    category: "Palette",
    image: p22_img, 
    new_price: 65000.00,
    old_price: 72000.00,
  },
  { id: 23, 
    name: "Zikel Rios Eyeshadow palette",
    category: "Palette",
    image: p23_img, 
    new_price: 65000.00,
    old_price: 72000.00,
  },
  { id: 24, 
    name: "18W Natural Wonder Artistry",
    category: "Palette",
    image: p24_img, 
    new_price: 55000.00,
    old_price: 65000.00,
  },
  { id: 25, 
    name: "Generic 120 Color Eyeshadow",
    category: "Palette",
    image: p25_img, 
    new_price: 68000.00,
    old_price: 76000.00,
  },
  { id: 26, 
    name: "Micellar Cleansing Water",
    category: "Cleanser",
    image: p26_img, 
    new_price: 15000.00,
    old_price: 20000.00,
  },
  { id: 27, 
    name: "Lemon Oil Cleanser",
    category: "Cleanser",
    image: p27_img, 
    new_price: 12000.00,
    old_price: 15000.00,
  },
  { id: 28, 
    name: "Gentle Eye Makeup Remover",
    category: "Cleanser",
    image: p28_img, 
    new_price: 14000.00,
    old_price: 18000.00,
  },
  { id: 29, 
    name: "Glow Natural Micellar Water",
    category: "Cleanser",
    image: p29_img, 
    new_price: 11000.00,
    old_price: 15000.00,
  },
  { id: 30, 
    name: "Moisturizing Makeup Remover & Cleanser",
    category: "Cleanser",
    image: p30_img, 
    new_price: 12000.00,
    old_price: 15000.00,
  },
  
];

export default ProductData;